AWSTemplateFormatVersion: "2010-09-09"

Description: Cloud Formation Template

Parameters:
  pVPCCIDR:
    Default: "10.0.0.0/16"
    Type: String
    Description: Please Enter the CIDR block for  VPC

  pPublicSubnet1CIDR:
    Default: "10.0.1.0/24"
    Type: String
    Description: Please Enter the CIDR block for Public Subnet-1

  pPublicSubnet2CIDR:
    Default: "10.0.2.0/24"
    Type: String
    Description: Please Enter the CIDR block for Public Subnet-2

  pPublicSubnet3CIDR:
    Default: "10.0.3.0/24"
    Type: String
    Description: Please Enter the CIDR block for Public Subnet-3

  AMIImage:
      Type: String
      Default: ami-0022f774911c1d690
      Description: Enter ami id

Resources:
    ### VPC Resources ###
  rVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref pVPCCIDR
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: "default"

  rPublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: "AWS::Region"
      VpcId: !Ref rVPC
      CidrBlock: !Ref pPublicSubnet1CIDR
      
  rPublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: "AWS::Region"
      VpcId: !Ref rVPC
      CidrBlock: !Ref pPublicSubnet2CIDR

  rPublicSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select
        - 2
        - !GetAZs
          Ref: "AWS::Region"
      VpcId: !Ref rVPC
      CidrBlock: !Ref pPublicSubnet3CIDR

  ### Internet Gateway ###
  rIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Internet-Gateway

  rIgwAssignVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref rIGW
      VpcId: !Ref rVPC

  ### Route Table ###
  rPublicSubnetRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      Tags:
        - Key: Name
          Value: Route Table
      VpcId: !Ref rVPC

  ### Attaching Route Table to public subnet ###

  rPublicSubnet1AssocRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rPublicSubnetRouteTable
      SubnetId: !Ref rPublicSubnet1

  rPublicSubnet2AssocRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rPublicSubnetRouteTable
      SubnetId: !Ref rPublicSubnet2

  rPublicSubnet3AssocRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rPublicSubnetRouteTable
      SubnetId: !Ref rPublicSubnet3

  ###  Adding   0.0.0.0/0to route  -> IGW ###
  rPublicSubnetRouteTableRouteEntry:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rIGW
      RouteTableId: !Ref rPublicSubnetRouteTable

  #EC2 Security Group
  applicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security group with ports
      GroupName: applicationSecurityGroup
      SecurityGroupIngress: [
          {
            "IpProtocol" : "tcp",
            "FromPort" : "22",
            "ToPort" : "22",
            "CidrIp" : "0.0.0.0/0"
          },
          {
            "IpProtocol" : "tcp",
            "FromPort" : "80",
            "ToPort" : "80",
            "CidrIp" : "0.0.0.0/0"
          },
          {
            "IpProtocol" : "tcp",
            "FromPort" : "443",
            "ToPort" : "443",
            "CidrIp" : "0.0.0.0/0"
          },
          {
            "IpProtocol" : "tcp",
            "FromPort" : "8080",
            "ToPort" : "8080",
            "CidrIp" : "0.0.0.0/0"
          }
        ]
      Tags:
        - Key: Name
          Value: EC2 Security Group
      VpcId: !Ref rVPC

  #EC2 Instance:
  EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !Ref AMIImage
        InstanceType: t2.micro
        KeyName: assignment3
        NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: applicationSecurityGroup
          SubnetId:
            Ref: rPublicSubnet1