AWSTemplateFormatVersion: "2010-09-09"

Description: Cloud Formation Template for an iotservice Implementation

Parameters:
  pVPCCIDR:
    Default: "10.0.0.0/16"
    Type: String
    Description: Please Enter the CIDR block for VPC

Resources:
  